import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'BBCode Templater Documentation',
  description: 'Generated by create next app',
};

export default function DocsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>
      <article className="prose-sm md:prose-base prose w-full max-w-4xl flex-grow">
        {children}
      </article>
    </main>
  );
}
