import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar';
import Footer from '@/components/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'BBCode Templater',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let initialTheme = 'default';
  if (typeof window !== 'undefined') {
    const theme = localStorage.getItem('theme');
    if (theme) {
      initialTheme = theme;
    }
  }

  return (
    <html lang="en" data-theme={initialTheme} suppressHydrationWarning>
      <body className={inter.className}>
        <Navbar />
        <div className="mx-auto w-full max-w-screen-xl p-3">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
